<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '96702619665613c2af7a3330265a21e1' => $baseDir . '/ext/http-method.php',
    'da43219b08adeb4037a8ba55d890243d' => $baseDir . '/ext/http-method.test.php',
);
