<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit49fbb4b248404b1d9ead2f596cfbd4ab
{
    public static $files = array (
        '96702619665613c2af7a3330265a21e1' => __DIR__ . '/../..' . '/ext/http-method.php',
        'da43219b08adeb4037a8ba55d890243d' => __DIR__ . '/../..' . '/ext/http-method.test.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SIKessEm\\HTTP\\Method\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SIKessEm\\HTTP\\Method\\' => 
        array (
            0 => __DIR__ . '/../..' . '/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit49fbb4b248404b1d9ead2f596cfbd4ab::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit49fbb4b248404b1d9ead2f596cfbd4ab::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit49fbb4b248404b1d9ead2f596cfbd4ab::$classMap;

        }, null, ClassLoader::class);
    }
}
